### PR TITLE
Fix corners

### PR DESCRIPTION
**Pull request by etiennesky**

### CODE REVIEW

**Comment by etiennesky** [comment]
Hi @JanStreffing Etienne from BSC here.  This MR fixes the grid cell corners (all but a few had 0 values) as well as fixing read access to the lsm file (writing is not required).

**Comment by JanStreffing** [comment]
Hello Etienne, thank you for your contribution!

**Comment by etiennesky** [comment]
thanks for such a quick turnaround! I don't know if anyone should be made aware hat grid corners computed with the tool are invalid.

**Comment by JanStreffing** [comment]
Perhaps I shall mention @uwefladrich and @joakimkjellsson here. I do not think anyone was using 2nd order conservative remapping thus far though. Which I think is the only reason to use the corner points. Correct me if I'm wrong there.

**Comment by etiennesky** [comment]
yes, this might be of interested to Uwe and the coupling task force.  I found this problem because I wanted to compute the gridcell corners of the EC-Earth3 T255 grid and I saw the bug.

**Pull request merged**
